// auto-generated by builder.js
// run "npm run build" to regenerate
// automatically rebuilt on push

import SurveyFactory from "./surveyFactory.jsx"
  
import exampleSurveyJson from "../surveys/exampleSurvey/exampleSurvey.json";
import exampleSurveySha from "../surveys/exampleSurvey/sha.json";
import { default as exampleSurveyScoreFunc } from "../surveys/exampleSurvey/exampleSurvey.score.js";
export const ExampleSurvey = SurveyFactory("exampleSurvey", exampleSurveyJson, exampleSurveyScoreFunc, exampleSurveySha);
  